# Generated by Django 4.1.7 on 2023-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='information',
            field=models.TextField(max_length=1000),
        ),
    ]
