# Generated by Django 4.1.7 on 2023-11-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_history', '0002_alter_history_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='client_first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='client_last_name',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='client_phone',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='coast',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user_first_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user_last_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user_otdel',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user_phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
