# Generated by Django 4.1.7 on 2023-11-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_history', '0003_history_client_first_name_history_client_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2023-11-16'),
            preserve_default=False,
        ),
    ]
